language: java

jdk:
  - oraclejdk8

sudo: true

before_install:
    apt-get install redis-server

    apt-get install firefox

    apt-get install xvfb firefox

    redis-server &

install:
    mvn install -DskipTests=true

before_script:
    mvn test -Dtest=DatabaseTalkieTest

    mvn test -Dtest=SaveTicketTest

    xvfb-run mvn test -Dtest=SeleniumTest