language: java

jdk:
  - oraclejdk8

sudo: true

before_install:
    apt-get install redis-server

    redis-server &

install:
    mvn install -DskipTests=true

before_script:
    mvn test

script:
    mvn package

    mvn install

    mvn deploy

deploy:
  provider: openshift
  user: 3danimanimal@gmail.com
  password: putoruby
  domain: dsq