language: java

jdk:
    - oraclejdk8

sudo: true

before_install:
    apt-get install redis-server

    apt-get install firefox

    apt-get install xvfb firefox

    - "export DISPLAY=:99.0"
    - "sh -e /etc/init.d/xvfb start"

    redis-server &

install:
    mvn install -DskipTests=true

before_script:
    mvn test -Dtest=DatabaseTalkieTest

    mvn test -Dtest=SaveTicketTest