language: java

jdk:
  - oraclejdk8

sudo: true

before_install:
    apt-get install redis-server
    redis-server

deploy:
  provider: openshift
  user: 3danimanimal@gmail.com
  password: putoruby
  domain: dsq